name: Cluster Config CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'cluster-config/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cluster-config/**'

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_CONFIG }}

      - name: Install kustomize and kubectl
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Build manifests
        run: |
          kustomize build cluster-config/overlays/dev > manifest.yaml

      - name: Validate manifests
        run: |
          if ! kubectl apply --dry-run=client -f manifest.yaml; then
            echo "❌ Manifest validation failed"
            exit 1
          fi
          echo "✅ Manifest validation passed"

      - name: Deploy to cluster
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          gcloud container clusters get-credentials dievops-cluster \
            --region us-central1 \
            --project ${{ env.PROJECT_ID }}
          kubectl apply -f manifest.yaml
