name: Cluster Config CI

on:
  push:
    paths:
      - 'cluster-config/**'

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
          service_account:          ${{ secrets.GCP_SERVICE_ACCOUNT_CONFIG }}

      - name: Install kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      - name: Build manifests
        run: |
          kustomize build cluster-config/overlays/dev > manifest.yaml

      # Placeholder: integrate Cloud Deploy or Config Sync when manifests estén listos
      - name: Show manifest size
        run: |
          wc -l manifest.yaml
